modLoader="javafml"
loaderVersion="[47,)"

license="All Rights Reserved"
issueTrackerURL="https://github.com/MinecraftForge/MinecraftForge/issues"
showAsResourcePack=false

[[mods]]
  modId="dramallama"
  version="0.0.1"
  displayName="Drama Llama"
  updateJSONURL="https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json"
  displayURL="https://minecraftforge.net"
  logoFile="logo.png"
  credits="I'd like to thank all the people that helped me"
  authors="Guardian_606,Juryjr,Techgeddon"
  description='''
  Llamas cause a lot of Drama
  '''
  displayTest="MATCH_VERSION"

[[dependencies.examplemod]]
  modId="forge"
  mandatory=true
  versionRange="[47,)"
  ordering="NONE"
  side="BOTH"

[[dependencies.examplemod]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.20.1]"
  ordering="NONE"
  side="BOTH"